### ISSUE TITLE
Error: Failed to fetch a lazy token - blocked by Cloudflare?

### ISSUE THREAD

**Issue by lss233** [realcoloride/node_characterai#1]
When I was running the example code, it raised following exception:  

```
Error: Failed to fetch a lazy token
      at Client.authenticateAsGuest (/home/lss233/project/node_modules/node_characterai/client.js:207:22)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at <anonymous> (/home/lss233/project/plugins/character-ai/src/index.ts:35:7)
```

I tired to print out the `request`, It shows follwing:  
```js
  [Symbol(Response internals)]: {
    type: 'default',
    url: 'https://beta.character.ai/chat/auth/lazy/',
    status: 403,
    statusText: 'Forbidden',
    headers: {
      'cache-control': 'private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0',
      'cf-ray': '795d56563f192ae9-LAX',
      connection: 'close',
      'content-encoding': 'gzip',
      'content-type': 'text/html; charset=UTF-8',
      date: 'Tue, 07 Feb 2023 16:00:13 GMT',
      expires: 'Thu, 01 Jan 1970 00:00:01 GMT',
      'referrer-policy': 'same-origin',
      server: 'cloudflare',
      'server-timing': 'cf-q-config;dur=6.9999996412662e-06',
      'set-cookie': '__cf_bm=fGFX6BoxOEm01ZuoCPM9886gf89xMl7oKfPfezzJig7Wo-1675785613-0-AS5g4Pb+ReO3jBcKFPLGLsbM3cFUPyzDJZg5FvHd70IARJJ7lPfUpUxWLtsJDJL7vesH5zQF78SzahQvqcSrk=; path=/; expires=Tue, 07-Feb-23 16:30:13 GMT; domain=.character.ai; HttpOnly; Secure; SameSite=None',
      'transfer-encoding': 'chunked',
      vary: 'Accept-Encoding',
      'x-frame-options': 'SAMEORIGIN'
    },
    counter: 0,
    highWaterMark: 16384
  }
}
```
It seems that they have Cloudflare AntiBot enabled.

**Comment by realcoloride** [comment]
That isn't normal, could you send me the piece of code? Also, try updating
to the latest version and see if it works.

**Comment by lss233** [comment]
Node version: v16.19.0
node_characterai: 1.0.17
```ts
import fetch from 'node-fetch';
const HttpsProxyAgent = require('https-proxy-agent');
const CharacterAI = require('node_characterai');
const characterAI = new CharacterAI();

globalThis.fetch = (url: RequestInfo | URL, options: RequestInit) => {
  return fetch(url, {
    agent: HttpsProxyAgent('http://172.22.208.1:10810'),
    ...options
  })
}
await characterAI.authenticateAsGuest();

const characterId = "8_1NyR8w1dOXmI1uWaieQcd147hecbdIK7CeEAIrdJw" // Discord moderator

const chat = await characterAI.createOrContinueChat(characterId);
const response = await chat.sendAndAwaitResponse(argv.args.join(' '), true)
```

I have to replace `fetch` with `node-fetch` because I cannot connect to the server directly without proxy.

**Comment by lss233** [comment]
I also tried curl, it has error too.
```bash
curl --location --request POST 'https://beta.character.ai/chat/auth/lazy/' \
--header 'Content-Type: application/json' \
--header 'Cookie: __cf_bm=RbaY5rYyFvMZVcVFE6YJ0Rgk804aWePlqQUB8ACOzlM-1675785383-0-AZCWYNkYNFJprIPmJ+Z+U+v1QdUYYUXxfZRsBj2CVSyxi4bMufRoG6gFssADcEbfwV/Qi11GlnhWYa+hiH+YZAg=; __cfwaitingroom=ChhFcUlveGRFQk5pdVB3dDk1S2QyZnlnPT0SlAIvS1FxV3N3bUF1ZXpoNUhIanB5SFc2djc3VFNiL1ZydDRXZmdxZHN3azRaQTh0Tmx0amZITlJEalVmdGczcHA2c0ZyQTU0cjRIN3JEYjdURmQ1SitVbk9rTWk4d1pPY2ZyREVCbWdzMTU0Qm95WlU5SGc2ZnRpcHc5SXNvNURkSFZqenhoZEFBWGsxK2xCT3F3a2NmQkN2NjlIb01aV1gyeG1qQVEvSmZYQXR2bEp3c1RiVkkyUXg4TkhnczRNeDY1NUtZZ0pGdXZaSWJzZjJUQTF5eGh4R2IzR2NGbEFjenNKR0M5Vm9qdUJ4SHRaT0k5N0Njb1R1NUJweTE0N1h3MmxzdGtJRUxLTDYxSEZQck1rMD0%3D; csrftoken=RATHLAweU2vrADFyg8riQt2ClxWVdCnw; sessionid=a52vzeia0a8fq5j6vdlbcwbmldj2yrv4' \
--data-raw '{
    "lazy_uuid": "eb711c64-934a-4775-9b11-e082d6618dc1"
}'
error code: 1020
```

**Comment by realcoloride** [comment]
Is your IP banned? Does your DNS not allow the website? Thats weird. I've tried it myself and it worked.

**Comment by realcoloride** [comment]
Also, is your code running in an asynchronous context?

**Comment by K3YOMI** [comment]
Having the same issue as well.

**Comment by realcoloride** [comment]
Hello! Could you tell me where the issue was exactly and how you fixed it?
What did you specify in the user agent/token variable?

_If any further issues happen:_
They might have changed the way (guest users) work (using lazy tokens). For my case, when I last used, it worked properly. If the same issue seems to continue, i will look indepth. Please note that guest accounts have 5-10 messages for free before prompted to login ("maximum messages reached").

If you have any questions in the meantime, please let me know and I will look further in later on.

Good luck and have fun!

**Comment by realcoloride** [comment]
Hello OP!

Do you still need help?
