### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by codeblitz97** [realcoloride/node_characterai#153]
When I first example code shown on the readme, it returns this error:

```sh
F:\ncai\node_modules\node_characterai\chat.js:70
            for (let i = 0; i < replies.length; i++) {
                                        ^
TypeError: Cannot read properties of undefined (reading 'length')
    at Chat.sendAndAwaitResponse (F:\ncai\node_modules\node_characterai\chat.js:70:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async F:\ncai\index.js:14:20
```

I also tried using authentication, it throws the same error

**Comment by codeblitz97** [comment]
Nevermind, fixed.

**Comment by SeoulSKY** [comment]
How did you fix the issue? I'm getting the same error

**Comment by codeblitz97** [comment]
@SeoulSKY It happens when you authenticate with guest. You have to authenticate with your session token first then you can interact with your ai.
You can modify this code as you like:

```js
const CharacterAI = require('node_characterai');
const readline = require('readline');
const characterAI = new CharacterAI();
require('dotenv').config();

function getUserInput(question) {
  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
  });

  return new Promise((resolve) => {
    rl.question(question, (answer) => {
      rl.close();
      resolve(answer);
    });
  });
}

(async () => {
  await characterAI.authenticateWithToken(process.env.SESSION_TOKEN);

  const characterId = process.env.CHARACTER_ID;

  const chat = await characterAI.createOrContinueChat(characterId);

  while (true) {
    const userInput = await getUserInput('You: ');
    const response = await chat.sendAndAwaitResponse(userInput, true);

    console.log('AI:', response.text);
  }
})();
```

**Comment by SeoulSKY** [comment]
Thank you so much! As you suggested, I tried using my own token instead of the guest token, and the example in README.md now works.

**Comment by realcoloride** [comment]
Hello, this seems related to #155
I will keep you updated.

**Comment by realcoloride** [comment]
Hello, please see #155.
