### ISSUE TITLE
Cannot find module “fs/promises”

### ISSUE THREAD

**Issue by Parking-Master** [realcoloride/node_characterai#50]
I am new to this package. Everytime I run the program it fails with this message.

I have installed “fs” and imported, but it is still throwing this error.

```javascript
pi@raspberrypi:~ $ node ai1.js

Error: Cannot find module 'fs/promises'
Require stack:
- /home/pi/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserFetcher.js
- /home/pi/node_modules/puppeteer-core/lib/cjs/puppeteer/node/node.js
- /home/pi/node_modules/puppeteer-core/lib/cjs/puppeteer/puppeteer-core.js
- /home/pi/node_modules/puppeteer/lib/cjs/puppeteer/puppeteer.js
- /home/pi/ai1.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/pi/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserFetcher.js:36:20)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/pi/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserFetcher.js',
    '/home/pi/node_modules/puppeteer-core/lib/cjs/puppeteer/node/node.js',
    '/home/pi/node_modules/puppeteer-core/lib/cjs/puppeteer/puppeteer-core.js',
    '/home/pi/node_modules/puppeteer/lib/cjs/puppeteer/puppeteer.js',
    '/home/pi/ai1.js'
  ]
}
```

This is the only file I am using:

###### ai1.js
```javascript

const CharacterAI = require('node_characterai');
const characterAI = new CharacterAI();
const puppeteer = require("puppeteer");

(async() => {
    await characterAI.authenticateWithToken("xxx");

    const characterId = "xxx" // Discord moderator

    const chat = await characterAI.createOrContinueChat(characterId);
    const response = await chat.sendAndAwaitResponse('Hello discord mod!', true)

    console.log(response);
    // use response.text to use it in a string.
})();
```

**Comment by DutaKey** [comment]
why u using `require("fs").promises;` ?

**Comment by Parking-Master** [comment]
Ok, I changed `require("fs/promises");` to `require("fs").promises;` on all the files the error was thrown on. It's a little better now, but now I am getting this error

```bash
pi@raspberrypi:~ $ node ai1.js
[node_characterai] Puppeteer - This is an experimental feature. Please report any issues on github.

  Puppeteer old Headless deprecation warning:
    In the near feature `headless: true` will default to the new Headless mode
    for Chrome instead of the old Headless implementation. For more
    information, please see https://developer.chrome.com/articles/new-headless/.
    Consider opting in early by passing `headless: "new"` to `puppeteer.launch()`
    If you encounter any bugs, please report them to https://github.com/puppeteer/puppeteer/issues/new/choose.

(node:2097) UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process!
/home/pi/.cache/puppeteer/chrome/linux-1108766/chrome-linux/chrome: 10: Syntax error: Unterminated quoted string


TROUBLESHOOTING: https://pptr.dev/troubleshooting

    at Interface.onClose (/home/pi/node_modules/@puppeteer/browsers/lib/cjs/launch.js:262:24)
    at Interface.emit (events.js:326:22)
    at Interface.close (readline.js:416:8)
    at Socket.onend (readline.js:194:10)
    at Socket.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:2097) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2097) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by realcoloride** [comment]
Hello, any error related to puppeteer (unless related to the package) is not my responsability and should be reported to puppeteer's package directly.
In node_characterai (not the dependencies), thare are no mention of the package `fs`.

**Comment by Parking-Master** [comment]
@realcoloride is there a way to use node_characterai without puppeteer? Puppeteer seems pretty buggy and every time I fix an error with it another one occurs. It never works no matter what I do.

**Comment by realcoloride** [comment]
Puppeteer was not used back then, only node-fetch. However, due to extremely strict and aggressive anti-scrapping measures, the only solution is to use puppeteer.
