### ISSUE TITLE
Puppeteer headless Deprecation error

### ISSUE THREAD

**Issue by ftk789** [realcoloride/node_characterai#51]
``[node_characterai] Puppeteer - This is an experimental feature. Please report any issues on github.
[1m[43m[30m
  Puppeteer old Headless deprecation warning:[0m[33m
    In the near feature `headless: true` will default to the new Headless mode
    for Chrome instead of the old Headless implementation. For more
    information, please see https://developer.chrome.com/articles/new-headless/.
    Consider opting in early by passing `headless: "new"` to `puppeteer.launch()`
    If you encounter any bugs, please report them to https://github.com/puppeteer/puppeteer/issues/new/choose.[0m

c:\Users\lolt0\node_modules\puppeteer\node_modules\puppeteer-core\lib\cjs\puppeteer\node\ProductLauncher.js:289
                    throw new Error(`Could not find Chromium (rev. ${this.puppeteer.browserRevision}). This can occur if either\n` +
                          ^

Error: Could not find Chromium (rev. 1108766). This can occur if either
 1. you did not perform an installation before running the script (e.g. `npm install`) or
 2. your cache path is incorrectly configured (which is: C:\Users\lolt0\.cache\puppeteer).
For (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration.
    at ChromeLauncher.resolveExecutablePath (c:\Users\lolt0\node_modules\puppeteer\node_modules\puppeteer-core\lib\cjs\puppeteer\node\ProductLauncher.js:289:27)
    at ChromeLauncher.executablePath (c:\Users\lolt0\node_modules\puppeteer\node_modules\puppeteer-core\lib\cjs\puppeteer\node\ChromeLauncher.js:182:25)
    at ChromeLauncher.computeLaunchArguments (c:\Users\lolt0\node_modules\puppeteer\node_modules\puppeteer-core\lib\cjs\puppeteer\node\ChromeLauncher.js:99:37)
    at ChromeLauncher.launch (c:\Users\lolt0\node_modules\puppeteer\node_modules\puppeteer-core\lib\cjs\puppeteer\node\ProductLauncher.js:83:39)
    at ChromeLauncher.launch (c:\Users\lolt0\node_modules\puppeteer\node_modules\puppeteer-core\lib\cjs\puppeteer\node\ChromeLauncher.js:53:22)
    at PuppeteerNode.launch (c:\Users\lolt0\node_modules\puppeteer\node_modules\puppeteer-core\lib\cjs\puppeteer\node\PuppeteerNode.js:150:105)
    at PuppeteerExtra.launch (c:\Users\lolt0\node_modules\puppeteer-extra\dist\index.cjs.js:128:41)
    at async Requester.initialize (c:\Users\lolt0\node_modules\node_characterai\requester.js:25:25)
    at async Client.authenticateAsGuest (c:\Users\lolt0\node_modules\node_characterai\client.js:197:9)``

**Comment by realcoloride** [comment]
Hello, for the deprecation error, I will fix it for the next update (as it was not happening before the update).
For the rest, such as your errors, you should try to probably install chromium, a chromium based browser (like chrome) or other.

**Comment by ftk789** [comment]
The thing is I do have Chrome installed, ( A chromium based browser ) And I still get the error....

**Comment by ftk789** [comment]
It works now after I installed Chrome Canary, Hope it get's fixed globally in the next update, Thank you for an amazing project.

**Comment by realcoloride** [comment]
Thank you for the support.

What environment were you using? Windows? Linux? was chrome installed on your C:/ Drive?

**Comment by ftk789** [comment]
> Thank you for the support.
> 
> What environment were you using? Windows? Linux? was chrome installed on your C:/ Drive?

Windows, Yes Chrome was intalled in the C:/ Drive.

**Comment by realcoloride** [comment]
Can you try specifying the executablePath in the requester?
It should be accessible at requester.js

In the next update I will try making it easier to specify an executablepath because a lot of people seem to have been getting issues about puppeteer recently.
Also if that helps, try putting the headless mode to new.

**Comment by ftk789** [comment]
> Can you try specifying the executablePath in the requester? It should be accessible at requester.js
> 
> In the next update I will try making it easier to specify an executablepath because a lot of people seem to have been getting issues about puppeteer recently. Also if that helps, try putting the headless mode to new.

`C:/Program Files/Google/Chrome/Application/chrome.exe` Specifically, That's where Chrome is.
