### ISSUE TITLE
How to interact with html?

### ISSUE THREAD

**Issue by KidLiumingjie** [realcoloride/node_characterai#55]
Thank you very much for your project, which made me come into contact with nodejs.

The code works fine, but I don't quite understand how to allow users to have a conversation on my webpage.

```
webserver.js
const http = require('http');
const fs = require('fs');
const express = require('express');
const path = require('path');

const app = express();


app.use(express.static(path.join(__dirname, 'page')));


app.get('/', (req, res) => {
  res.sendFile(path.join(__dirname, 'page', 'main.html'));
});


const server = http.createServer(app);

server.listen(3000, 'localhost', () => {
  console.log('server in 3000 port');
});
```
---------------------------------------------------------------------------------------------------------------------------------------------------
And another problem that i don't really know what happened.

```
test.js
const CharacterAI = require('node_characterai');
const readline = require('readline');

const characterAI = new CharacterAI();

(async () => {
  await characterAI.authenticateAsGuest();

  const characterId = "8_1NyR8w1dOXmI1uWaieQcd147hecbdIK7CeEAIrdJw"; // Discord moderator

  const chat = await characterAI.createOrContinueChat(characterId);

  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout
  });

  rl.setPrompt('You: ');
  rl.prompt();

  rl.on('line', async (input) => {
    const response = await chat.sendAndAwaitResponse(input.trim(), true);
    console.log('Bot:', response.text);

    rl.prompt();
  });

  rl.on('close', () => {
    console.log('Chat ended.');
  });
})();

```
then appear
```
C:\Users\USER\Downloads\node_characterai-main\node_modules\node_characterai\chat.js:71
            for (let i = 0; i < replies.length; i++) {
                                        ^

TypeError: Cannot read properties of undefined (reading 'length')
    at Chat.sendAndAwaitResponse (C:\Users\USER\Downloads\node_characterai-main\node_modules\node_characterai\chat.js:71:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Interface.<anonymous> (C:\Users\USER\Downloads\node_characterai-main\test.js:22:22)
```

**Comment by realcoloride** [comment]
You should have a look into websockets or sockets if you want real time communication between your server and client. However, a simple REST API can also do the job.

**Comment by KidLiumingjie** [comment]
I really appreciate your reply!!
The first problem has been solved.
